name: Deploy Flask App to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        source .venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive only required files
      run: |
        zip -r app.zip app.py dell_support.py requirements.txt templates uploads reports

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: dell-warranty
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: app.zip

    - name: Set app setting for build automation
      uses: azure/appservice-settings@v1
      with:
        app-name: dell-warranty
        app-settings-json: |
          [
             {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true"
            }
          ]
    - name: Set startup command
      uses: azure/appservice-settings@v1
      with:
        app-name: dell-warranty
        app-settings-json: |
          [
             {
              "name": "WEBSITE_RUN_FROM_PACKAGE",
              "value": "1"
            },
            {
              "name": "WEBSITE_PORT",
              "value": "8000"
            }
          ]
    - name: Configure Startup command
      uses: azure/appservice-settings@v1
      with:
        app-name: dell-warranty
        general-settings-json: |
          {
            "startupCommand": "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
          }
